### ISSUE TITLE
Noice issue

### ISSUE THREAD

**Issue by sayansinha2019** [luxiaolili/IDM-VTON-train#13]
Traceback (most recent call last):
  File "/home/ubuntu/IDM-VTON/IDM-VTON-train/train.py", line 550, in <module>
    main()
  File "/home/ubuntu/IDM-VTON/IDM-VTON-train/train.py", line 520, in main
    down,reference_features = UNet_Encoder(cloth_latents, timesteps, cloth_text_embeds,return_dict=False)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/IDM-VTON/IDM-VTON-train/src/unet_hacked_garmnet.py", line 1087, in forward
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1168, in launch_command
    simple_launcher(args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 763, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train.py', '--pretrained_model_name_or_path=yisol/IDM-VTON', '--inpainting_model_path=ckpt', '--garmnet_model_path=stabilityai/stable-diffusion-xl-base-1.0', '--width=768', '--height=1024', '--data_json_file=sayan_data.json', '--data_root_path=sayan_data', '--mixed_precision=bf16', '--train_batch_size=1', '

Any resolution for this?

**Comment by luxiaolili** [comment]
> Traceback (most recent call last): File "/home/ubuntu/IDM-VTON/IDM-VTON-train/train.py", line 550, in main() File "/home/ubuntu/IDM-VTON/IDM-VTON-train/train.py", line 520, in main down,reference_features = UNet_Encoder(cloth_latents, timesteps, cloth_text_embeds,return_dict=False) File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/home/ubuntu/IDM-VTON/IDM-VTON-train/src/unet_hacked_garmnet.py", line 1087, in forward if "text_embeds" not in added_cond_kwargs: TypeError: argument of type 'NoneType' is not iterable Traceback (most recent call last): File "/home/ubuntu/.local/bin/accelerate", line 8, in sys.exit(main()) File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main args.func(args) File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1168, in launch_command simple_launcher(args) File "/home/ubuntu/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 763, in simple_launcher raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd) subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train.py', '--pretrained_model_name_or_path=yisol/IDM-VTON', '--inpainting_model_path=ckpt', '--garmnet_model_path=stabilityai/stable-diffusion-xl-base-1.0', '--width=768', '--height=1024', '--data_json_file=sayan_data.json', '--data_root_path=sayan_data', '--mixed_precision=bf16', '--train_batch_size=1', '
> 
> Any resolution for this?
--inpainting_model_path = 'stable-diffusion-xl-1.0-inpainting-0.1' 
 You need change stable-diffusion-xl-1.0-inpainting-0.1 unet config update "encoder_hid_dim_type":"ip_image_proj", and "encoder_hid_dim":1280
stabilityai/stable-diffusion-xl-base-1.0 unet config delete "addition_embed_type":"text_time"

**Comment by sayansinha2019** [comment]
I updated the config but still same error.

**Comment by luxiaolili** [comment]
> I updated the config but still same error.
I check the code unet_hacked_garmnet.py, line 1087, You need delete garmnet unet's config about the "addition_embed_dtype". Go to the folder stabilityai/stable-diffusion-xl-base-1.0 unet config  delete "addition_embed_type":"text_time"
